# Generated by Django 5.2.8 on 2025-11-27 11:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCRForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CCR Form', max_length=200, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CCR Form',
                'verbose_name_plural': 'CCR Forms',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dynamic CCR Form', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Form',
                'verbose_name_plural': 'Dynamic Forms',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('course_collaborator', 'Course Collaborator'), ('faculty', 'Faculty')], default='faculty', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('credits', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ManyToManyField(blank=True, related_name='assigned_courses', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code_title', models.CharField(max_length=300)),
                ('course_coordinator', models.CharField(max_length=200)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('dynamic_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dynamicform')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('faculty', 'course', 'dynamic_form')},
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('checkbox', 'Checkbox'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('section_header', 'Section Header'), ('clo_review_table', 'CLO Review Table'), ('clo_domain_table', 'CLO Domain Table'), ('group_members', 'Group Members'), ('course_info', 'Course Information')], default='text', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('options', models.TextField(blank=True, help_text='For select/radio types, provide options separated by commas')),
                ('config', models.JSONField(blank=True, help_text='JSON configuration for complex question types', null=True)),
                ('help_text', models.TextField(blank=True, help_text='Additional help text for this question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.dynamicform')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('answer_data', models.JSONField(blank=True, help_text='Structured data for complex answers', null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.dynamicformsubmission')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.formquestion')),
            ],
        ),
        migrations.CreateModel(
            name='CCRSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code_title', models.CharField(max_length=300)),
                ('course_coordinator', models.CharField(max_length=200)),
                ('q1_topics_included', models.TextField(verbose_name='HEC topics coverage')),
                ('q2_topics_adjustments', models.TextField(verbose_name='Topics to add/remove')),
                ('q3_week_distribution', models.TextField(verbose_name='Week-wise distribution')),
                ('q4_books_relevance', models.TextField(verbose_name='Textbook relevance')),
                ('q5_prerequisite_course', models.TextField(verbose_name='Prerequisite course')),
                ('clo1_student_centered', models.BooleanField(default=False)),
                ('clo1_measurable', models.BooleanField(default=False)),
                ('clo1_achievable', models.BooleanField(default=False)),
                ('clo1_correct_verb', models.BooleanField(default=False)),
                ('clo2_student_centered', models.BooleanField(default=False)),
                ('clo2_measurable', models.BooleanField(default=False)),
                ('clo2_achievable', models.BooleanField(default=False)),
                ('clo2_correct_verb', models.BooleanField(default=False)),
                ('clo3_student_centered', models.BooleanField(default=False)),
                ('clo3_measurable', models.BooleanField(default=False)),
                ('clo3_achievable', models.BooleanField(default=False)),
                ('clo3_correct_verb', models.BooleanField(default=False)),
                ('clo4_student_centered', models.BooleanField(default=False)),
                ('clo4_measurable', models.BooleanField(default=False)),
                ('clo4_achievable', models.BooleanField(default=False)),
                ('clo4_correct_verb', models.BooleanField(default=False)),
                ('clo1_domain', models.CharField(blank=True, max_length=100)),
                ('clo1_level', models.CharField(blank=True, max_length=100)),
                ('clo1_ga_mapping', models.CharField(blank=True, max_length=100)),
                ('clo2_domain', models.CharField(blank=True, max_length=100)),
                ('clo2_level', models.CharField(blank=True, max_length=100)),
                ('clo2_ga_mapping', models.CharField(blank=True, max_length=100)),
                ('clo3_domain', models.CharField(blank=True, max_length=100)),
                ('clo3_level', models.CharField(blank=True, max_length=100)),
                ('clo3_ga_mapping', models.CharField(blank=True, max_length=100)),
                ('clo4_domain', models.CharField(blank=True, max_length=100)),
                ('clo4_level', models.CharField(blank=True, max_length=100)),
                ('clo4_ga_mapping', models.CharField(blank=True, max_length=100)),
                ('group_member_1', models.CharField(blank=True, max_length=200)),
                ('group_member_2', models.CharField(blank=True, max_length=200)),
                ('group_member_3', models.CharField(blank=True, max_length=200)),
                ('group_member_4', models.CharField(blank=True, max_length=200)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ccr_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ccrform')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
            ],
            options={
                'unique_together': {('faculty', 'course', 'ccr_form')},
            },
        ),
    ]
