# Generated by Django 5.2.8 on 2025-11-24 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCRForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CCR Form', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CCRSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code_title', models.CharField(max_length=300)),
                ('course_coordinator', models.CharField(max_length=200)),
                ('q1_topics_included', models.TextField(verbose_name='HEC topics coverage')),
                ('q2_topics_adjustments', models.TextField(verbose_name='Topics to add/remove')),
                ('q3_week_distribution', models.TextField(verbose_name='Week-wise distribution')),
                ('q4_books_relevance', models.TextField(verbose_name='Textbook relevance')),
                ('q5_prerequisite_course', models.TextField(verbose_name='Prerequisite course')),
                ('clo1_student_centered', models.BooleanField(default=False)),
                ('clo1_measurable', models.BooleanField(default=False)),
                ('clo1_achievable', models.BooleanField(default=False)),
                ('clo1_correct_verb', models.BooleanField(default=False)),
                ('clo2_student_centered', models.BooleanField(default=False)),
                ('clo2_measurable', models.BooleanField(default=False)),
                ('clo2_achievable', models.BooleanField(default=False)),
                ('clo2_correct_verb', models.BooleanField(default=False)),
                ('clo3_student_centered', models.BooleanField(default=False)),
                ('clo3_measurable', models.BooleanField(default=False)),
                ('clo3_achievable', models.BooleanField(default=False)),
                ('clo3_correct_verb', models.BooleanField(default=False)),
                ('clo4_student_centered', models.BooleanField(default=False)),
                ('clo4_measurable', models.BooleanField(default=False)),
                ('clo4_achievable', models.BooleanField(default=False)),
                ('clo4_correct_verb', models.BooleanField(default=False)),
                ('clo1_domain', models.CharField(blank=True, max_length=100)),
                ('clo1_level', models.CharField(blank=True, max_length=100)),
                ('clo1_ga_mapping', models.CharField(blank=True, max_length=100)),
                ('clo2_domain', models.CharField(blank=True, max_length=100)),
                ('clo2_level', models.CharField(blank=True, max_length=100)),
                ('clo2_ga_mapping', models.CharField(blank=True, max_length=100)),
                ('clo3_domain', models.CharField(blank=True, max_length=100)),
                ('clo3_level', models.CharField(blank=True, max_length=100)),
                ('clo3_ga_mapping', models.CharField(blank=True, max_length=100)),
                ('clo4_domain', models.CharField(blank=True, max_length=100)),
                ('clo4_level', models.CharField(blank=True, max_length=100)),
                ('clo4_ga_mapping', models.CharField(blank=True, max_length=100)),
                ('group_member_1', models.CharField(blank=True, max_length=200)),
                ('group_member_2', models.CharField(blank=True, max_length=200)),
                ('group_member_3', models.CharField(blank=True, max_length=200)),
                ('group_member_4', models.CharField(blank=True, max_length=200)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ccr_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ccrform')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('faculty', 'course', 'ccr_form')},
            },
        ),
    ]
