# Generated by Django 5.2.8 on 2025-12-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutline',
            name='content',
            field=models.TextField(blank=True, help_text='HTML content for course outline', null=True),
        ),
        migrations.AlterField(
            model_name='dynamicform',
            name='form_type',
            field=models.CharField(choices=[('ccr', 'CCR Form (Course Coordinators)'), ('crr', 'CRR Form (Regular Faculty)')], default='crr', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('crc_member', 'CRC Member')], default='faculty', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='courseoutline',
            unique_together={('course', 'faculty', 'version')},
        ),
    ]
