# Generated by Django 5.2.8 on 2025-11-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formquestion',
            name='config',
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='help_text',
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='options',
            field=models.TextField(blank=True, help_text='For select/radio/checkboxes, provide options separated by commas'),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('checkbox', 'Single Checkbox'), ('checkboxes', 'Multiple Checkboxes'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('section_header', 'Section Header')], default='text', max_length=20),
        ),
    ]
