# Generated by Django 5.2.8 on 2025-11-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ccrform_ccrsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccrform',
            options={'verbose_name': 'CCR Form', 'verbose_name_plural': 'CCR Forms'},
        ),
        migrations.AlterField(
            model_name='ccrform',
            name='name',
            field=models.CharField(default='CCR Form', max_length=200, unique=True),
        ),
    ]
