# Generated by Django 5.2.8 on 2025-11-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_formquestion_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='config',
            field=models.JSONField(blank=True, help_text='JSON configuration for complex question types', null=True),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='help_text',
            field=models.TextField(blank=True, help_text='Additional help text for this question'),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='options',
            field=models.TextField(blank=True, help_text='For select/radio types, provide options separated by commas'),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('checkbox', 'Checkbox'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('section_header', 'Section Header'), ('clo_review_table', 'CLO Review Table'), ('clo_domain_table', 'CLO Domain Table'), ('group_members', 'Group Members'), ('course_info', 'Course Information')], default='text', max_length=20),
        ),
    ]
