# Generated by Django 5.2.8 on 2025-11-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_formquestion_config_formquestion_help_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('checkbox', 'Checkbox'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('section_header', 'Section Header')], default='text', max_length=20),
        ),
    ]
