# Generated by Django 5.2.8 on 2026-01-28 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_department_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CQIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('semester', 'Semester Report'), ('annual', 'Annual Report'), ('department', 'Department Report'), ('course', 'Course Report')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('executive_summary', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('opportunities', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('form_submissions_summary', models.JSONField(blank=True, default=dict)),
                ('outline_approvals_summary', models.JSONField(blank=True, default=dict)),
                ('clo_achievement_summary', models.JSONField(blank=True, default=dict)),
                ('nlp_analysis', models.JSONField(blank=True, default=dict)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('key_themes', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutlineComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_data', models.JSONField(help_text='JSON containing comparison results')),
                ('added_lines', models.IntegerField(default=0)),
                ('modified_lines', models.IntegerField(default=0)),
                ('deleted_lines', models.IntegerField(default=0)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('compared_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('version1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_v1', to='accounts.courseoutline')),
                ('version2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_v2', to='accounts.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('ccr', 'CCR Form (Course Coordinators)'), ('crr', 'CRR Form (Regular Faculty)')], max_length=20)),
                ('submission_date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('faculty_department', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Submission Analytics',
                'unique_together': {('form_type', 'submission_date', 'faculty_department')},
            },
        ),
        migrations.CreateModel(
            name='CLOAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clo_number', models.IntegerField()),
                ('achievement_rate', models.FloatField(default=0.0)),
                ('total_students', models.IntegerField(default=0)),
                ('passing_students', models.IntegerField(default=0)),
                ('semester', models.CharField(max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_achievements', to='accounts.course')),
                ('outline_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.courseoutline')),
            ],
            options={
                'unique_together': {('course', 'clo_number', 'semester')},
            },
        ),
    ]
