# Generated by Django 6.0.7 on 2026-07-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cqireport_outlinecomparison_submissionanalytics_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cloachievement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cloachievement',
            name='course',
        ),
        migrations.RemoveField(
            model_name='cloachievement',
            name='outline_version',
        ),
        migrations.RemoveField(
            model_name='cqireport',
            name='course',
        ),
        migrations.RemoveField(
            model_name='cqireport',
            name='department',
        ),
        migrations.RemoveField(
            model_name='cqireport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='outlinecomparison',
            name='course',
        ),
        migrations.RemoveField(
            model_name='outlinecomparison',
            name='version1',
        ),
        migrations.RemoveField(
            model_name='outlinecomparison',
            name='version2',
        ),
        migrations.DeleteModel(
            name='SubmissionAnalytics',
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('checkbox', 'Checkbox'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('section_header', 'Section Header'), ('file', 'File Upload'), ('clo_percentage', 'CLO Percentage')], default='text', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='coursefaculty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_coordinator', True)), fields=('course',), name='unique_coordinator_per_course'),
        ),
        migrations.DeleteModel(
            name='CLOAchievement',
        ),
        migrations.DeleteModel(
            name='CQIReport',
        ),
        migrations.DeleteModel(
            name='OutlineComparison',
        ),
    ]
