# Generated by Django 6.0.7 on 2026-07-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_unique_coordinator_per_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='catalogue_file',
            field=models.FileField(blank=True, null=True, upload_to='course_catalogues/'),
        ),
    ]
