# Generated by Django 6.0.7 on 2026-07-21 22:11

from django.db import migrations, models


def migrate_legacy_sections(apps, schema_editor):
    CourseFaculty = apps.get_model('accounts', 'CourseFaculty')
    Section = apps.get_model('accounts', 'Section')

    for assignment in CourseFaculty.objects.all():
        legacy_section = (getattr(assignment, 'section', None) or '').strip()
        if not legacy_section:
            continue

        # Support comma-separated legacy values
        parts = [part.strip() for part in legacy_section.split(',') if part.strip()]
        section_ids = []
        for part in parts:
            code = part[:20]
            section, _created = Section.objects.get_or_create(
                code=code,
                defaults={'name': part, 'description': 'Migrated from legacy section field'},
            )
            section_ids.append(section.id)
        if section_ids:
            assignment.sections.set(section_ids)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_course_catalogue_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='coursefaculty',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='faculty_assignments', to='accounts.section'),
        ),
        migrations.RunPython(migrate_legacy_sections, noop_reverse),
        migrations.RemoveField(
            model_name='coursefaculty',
            name='section',
        ),
    ]
