# Generated by Django 6.0.7 on 2026-07-21 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_section_model_and_coursefaculty_m2m'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dynamicformsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dynamicformsubmission',
            name='assigned_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_submissions', to='accounts.section'),
        ),
        migrations.AddConstraint(
            model_name='dynamicformsubmission',
            constraint=models.UniqueConstraint(fields=('faculty', 'course', 'dynamic_form', 'assigned_section'), name='unique_form_submission_per_section'),
        ),
    ]
