# Generated by Django 6.0.7 on 2026-07-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_link_legacy_submission_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicform',
            name='form_type',
            field=models.CharField(choices=[('ccr', 'CCR Form (Course Coordinators)'), ('crr', 'CRR Form (Regular Faculty)'), ('lrr', 'LRR Form (Lab Instructors)')], default='crr', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('crc_member', 'CRC Member'), ('lab_instructor', 'Lab Instructor')], default='faculty', max_length=30),
        ),
    ]
