# Generated by Django 6.0.7 on 2026-07-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_lab_instructor_and_lrr'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformsubmission',
            name='submission_mode',
            field=models.CharField(choices=[('form', 'Filled Form'), ('file', 'Uploaded File')], default='form', max_length=20),
        ),
        migrations.AddField(
            model_name='dynamicformsubmission',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='review_form_uploads/'),
        ),
    ]
