# Generated by Django 6.0.7 on 2026-07-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_backfill_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_lab',
            field=models.BooleanField(default=False, help_text='Mark as a lab course. LRR forms are only available for lab courses.'),
        ),
    ]
